### ISSUE TITLE
Translators not allowed as attribute of contributors

### ISSUE THREAD

**Issue by MarvinSchenkel** [athombv/node-homey-lib#154]
When I try to give someone credit for translating my app, as documented in https://apps.developer.athom.com/tutorial-App%20Store.html, I get an error:

× Homey App did not validate against level `debug`:
[
    {
        "keyword": "additionalProperties",
        "dataPath": ".contributors",
        "schemaPath": "#/properties/contributors/additionalProperties",
        "params": {
            "additionalProperty": "translators"
        },
        "message": "should NOT have additional properties"
    }
]

**Comment by bvdbos** [comment]
https://github.com/athombv/node-homey-lib/blob/85d3d2b903f48405a123bb21cea2a54c87be39b9/assets/app/schema.json#L648-L659 according to @robertklep

**Comment by WeeJeWel** [comment]
Fixed
