### ISSUE TITLE
allowedCapabilityTypes should support 'object'

### ISSUE THREAD

**Issue by irritanterik** [athombv/node-homey-lib#23]
Object typed capabilities are needed for capabilities like long latitude locations or other multi-dimensional datapoints. 
This is an undocumented breaking change as of version 0.9.1.

**Comment by WeeJeWel** [comment]
That would be really hard to validate. Wouldn't `string` suffice in this case? e.g. `50.654,7.3484`

**Comment by irritanterik** [comment]
I'll try to get it working with a `string` and `JSON.stringify()`, but don't like the coding and decoding nessacary in backend and frontend when implementing custom mobile cards.

**Comment by WeeJeWel** [comment]
Hm, as custom components aren't supported for now, how would you then display it in a mobile card?

**Comment by irritanterik** [comment]
Ah. Thought it was supported as of v 0.9.1. My mistake. Eventually want to do something like:
![image](https://cloud.githubusercontent.com/assets/15232724/17289957/43cce548-57dc-11e6-89f8-237d6ea5afb8.png)

**Comment by WeeJeWel** [comment]
Alright. When creating support for custom mobile cards I'll keep that in mind!

**Comment by irritanterik** [comment]
Thanks. Close this issue for now.
