### ISSUE TITLE
Warning for `titleFormatted is missing` on card to connect to device

### ISSUE THREAD

**Issue by runely** [athombv/node-homey-lib#313]
My custom flow is connected to `garagedoor` class and put into each device connected through my app. To accomplish this i'm using this code in the flow:
```json
"args": [
    {
      "name": "device",
      "type": "device",
      "filter": "class_id=garagedoor"
    }
  ]
```

Adding a `titleFormatted` for only this argument makes no sense since the argument isn't available to the user in the flow editor anyway.

**Comment by WeeJeWel** [comment]
Hey! A titleFormatted is on the card-level, not on the argument-level.

It's okay to use the same string for both title and titleFormatted if your only argument is a device.

**Comment by runely** [comment]
Sorry. I meant card, not flow...

Okey, then i can create a titleFormatted with the same text, although i think that's unnecessary for a card not actually needing a titleFormatted

```json
{
  "title": {
    "en": "Left open",
    "no": "Stått åpen"
  },
  "hint": {
    "en": "Triggered when garage door has been left open for the specified duration set in 'Notify if left open' setting in the Remootio app (minimum value 5 minutes)",
    "no": "Utløses når garasjeporten har stått åpen i den angitte varigheten satt i 'Notify if left open' innstillingen i Remootio appen (minsteverdi er 5 minutter)"
  },
  "tokens": [
    {
      "type": "string",
      "name": "name",
      "title": {
        "en": "Device name",
        "no": "Enhetsnavn"
      }
    },
    {
      "type": "number",
      "name": "duration",
      "title": {
        "en": "Duration",
        "no": "Varighet"
      }
    }
  ],
  "args": [
    {
      "name": "device",
      "type": "device",
      "filter": "class_id=garagedoor"
    }
  ]
}
```

**Comment by runely** [comment]
Setting `titleFormatted` equal to `title` did not work

![image](https://user-images.githubusercontent.com/25814673/133888850-7a39d999-6744-4069-a5f2-e75c171dd669.png)

**Comment by runely** [comment]
Since the only argument is the device, and this argument is never shown to the user, requiring a `titleFormatted` seems unnecessary.

Maybe this test should take this into consideration and don't require a `titleFormatted` for these circumstances

**Comment by WeeJeWel** [comment]
Hey, sorry, I only now took a closer look at your code.

You should use `driver_id=` in your filter as well. If not, the card is rendered as an autocomplete with all of the user's paired devices of that app.

**Comment by runely** [comment]
That fixes it. Thanks 👍
