### ISSUE TITLE
`Date and time` trigger card triggers 1 minute too late on 7.1.4

### ISSUE THREAD

**Issue by runely** [athombv/node-homey-lib#318]
After Homey got updated to **7.1.4** the `Date and time` trigger card triggers 1 minute too late.

My flow to lock the front door at 19:00 every day now fires at 19:01.

Also mentioned here: https://athomcommunity.slack.com/archives/C04E9KJAD/p1632577012177200

![image](https://user-images.githubusercontent.com/25814673/135900355-371cf810-375a-432e-9653-fade92f85f0a.png)
![image](https://user-images.githubusercontent.com/25814673/135900422-3286c909-3a6f-4d1b-8e91-44ac0c68652c.png)
![image](https://user-images.githubusercontent.com/25814673/135900287-e2367737-64a7-4059-892b-324a2af4c25a.png)

**Comment by tjallingt** [comment]
We believe this issue was fixed a while back, if you encounter this problem again please make an issue at: https://github.com/athombv/homey-apps-sdk-issues/issues or reach out to the support at https://support.homey.app/hc/en-us/requests/new
