### ISSUE TITLE
Add measure_current and measure_voltage capabilities, update measure_power capability

### ISSUE THREAD

**Issue by TedTolboom** [athombv/node-homey-lib#36]
The Neo Power plug reports next to the electrical power and energie, the current and voltage... 
These are not yet standard capabilities.

For the Neo power plug, I added them as custom capabilities (simple copy of current measure power capability), added the corresponding icons and updated the current measure_power icon (including P).

<img width="341" alt="schermafbeelding 2017-01-03 om 22 51 40" src="https://cloud.githubusercontent.com/assets/17163431/21626796/a2f09c3e-d213-11e6-99d7-67f3201c35f2.png">
<img width="341" alt="schermafbeelding 2017-01-03 om 22 51 29" src="https://cloud.githubusercontent.com/assets/17163431/21626797/a304cdda-d213-11e6-870d-eb0cb72bfc2a.png">

Please include these into the standard capabilities.

See attached documents
[Additional measure capabilities and icons.zip](https://github.com/athombv/homey/files/683467/Additional.measure.capabilities.and.icons.zip)

**Comment by WeeJeWel** [comment]
Thanks! Added, and will be used in the next release of Homey
