### ISSUE TITLE
Add alarm_presence capability

### ISSUE THREAD

**Issue by hive** [athombv/node-homey-lib#420]
Sensors have evolved, and now tracking presence is not only possible but preferred in many case, this also applies to virtual devices and flows for setting room activity based on presence. Presence is different to motion and some devices are now offering both a motion and presence sensor.

Can we please get a offical presence capability.

**Comment by RobinBol** [comment]
Capability `alarm_presence` has been added!
https://github.com/athombv/node-homey-lib/blob/develop/assets/capability/capabilities/alarm_presence.json
