### ISSUE TITLE
2 decimals in alarm generic boolean capability ?

### ISSUE THREAD

**Issue by nattlip** [athombv/node-homey-lib#75]
"alarm_generic": {
			"type": "boolean",
			"title": {
				"en": "Generic Alarm",
				"nl": "Algemeen Alarm"
			},
			"desc": {
				"en": "Generic alarm",
				"nl": "Algemeen alarm"
			},
			"decimals": 2,
			"getable": true,
			"setable": true
		},

i dont understand why 2 decimals for a boolean capability ?

**Comment by WeeJeWel** [comment]
Good call, fixed
